### ISSUE TITLE
can't compile with gdal-2.1.2 

### ISSUE THREAD

**Issue by bleutner** [mappl/scidb4gdal#11]
Hi, 

I just wanted to give your interesting driver and scidb solution a go, but failed to compile it (gdal-2.1.2 with gcc 2.6.0, ubuntu 16.10)
Are there specific gdal or compiler requirements? GDAL itself compiles without problems.

Adding your driver files to the gdal source still works fine with gdal-2.1.2, even based on the original line-numbers.

Here are the full log files for [configure](https://github.com/appelmar/scidb4gdal/files/648602/configure_log.txt) and [make](https://github.com/appelmar/scidb4gdal/files/648601/make_log.txt).

Here's an excerpt:
```
1997:parameter_parser.cpp:30:77: error: ambiguous overload for 'operator=' (operand types are 'std::map<std::__cxx11::basic_string<char>, scidb4gdal::Properties, std::less<std::__cxx11::basic_string<char> >, std::allocator<std::pair<const std::__cxx11::basic_string<char>, scidb4gdal::Properties> > >' and 'boost::assign_detail::generic_list<std::pair<const char*, scidb4gdal::Properties> >')
1998-         "CHUNKSIZE_T", CHUNKSIZE_TEMPORAL)("chunksize_t", CHUNKSIZE_TEMPORAL);
1999-                                                                             ^
2000-In file included from /usr/include/c++/6/map:61:0,
2001-                 from /media/wd1/sources/gdal-2.1.2/gcore/gdal_priv.h:69,
2002-                 from /media/wd1/sources/gdal-2.1.2/gcore/gdal_pam.h:33,
2003-                 from utils.h:81,
2004-                 from shim_client_structs.h:5,
2005-                 from parameter_parser.h:4,
2006-                 from parameter_parser.cpp:1:
```

Cheers,
Benjamin

**Comment by appelmar** [comment]
Thanks for the report, Benjamin. Could you try with the dev branch? I remember some similar issues, which I fixed in [50de4b857075570dd6015695d17f3d74597995b3](https://github.com/appelmar/scidb4gdal/commit/50de4b857075570dd6015695d17f3d74597995b3). Please let me know if that works.

**Comment by bleutner** [comment]
Great! Compiling with your dev branch is successful. I'm looking forward to give it a go.

By the way: is your work somehow related to the efforts in the [e-sensing repository](https://github.com/e-sensing/scietl)? It looks like your aims are very similar.

**Comment by appelmar** [comment]
Cool, I'll close the issue, let me know if you have any further questions. We had some collaborations with the e-sensing members, though the projects have a slightly different approach to load data to SciDB. As far as I know, SciETL writes binary files whereas this GDAL driver writes directly to SciDB over HTTP.  Both approaches may have their advantages.

**Comment by bleutner** [comment]
thanks!
